application:
  name: OAuthServer
server:
  port: 8980
  ssl:
    enabled: true
    key-alias: skipper
    key-store: "src/main/resources/key.keystore"
    key-store-type: jks
    key-store-password: password
    key-password: password


app:
  oauth:
    client-id: client
    client-secret: secret
    token:
     key: access_token
